### ISSUE TITLE
META ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/depviz-action#1]
* [ ] initial version that allows a project to have automatic depviz without effort and minimal configuration (See https://github.com/moul/depviz/issues/658)
* [ ] bonus: optimize installation time
* [ ] bonus: use cache for indexes.bolt
